spring:
    application:
        name: upbit

trade:
    key:
        first_coin: fisrtCoin
        second_coin: secondCoin
        buy_price: buyPrice
        sell_price: sellPrice
        profit_margin: profitMargin
        loss_margin: lossMargin
        trade_price: trade_price
upbit:
    # MySQL DB 설정 필수
    access_key: accessKey
    secret_key: secretKey

        
